name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          .spago
          output
          node_modules
        key: build-atrifacts-v2-${{ hashFiles('package-lock.json', 'spago.dhall', 'packages.dhall') }}
    - uses: actions/setup-node@v1
      with:
        node-version: 16.15.1
    - run: npm i
    - run: npm run build
    - run: npm run test
